# Generated by Django 2.1.7 on 2019-03-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190327_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
