# Generated by Django 2.1.7 on 2019-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190327_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('periodo', 'siglas', 'username'), 'verbose_name': 'Aspirante', 'verbose_name_plural': 'Aspirantes'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
