# Generated by Django 2.1.7 on 2019-03-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='TimeRecord',
        ),
    ]
