# Generated by Django 2.1.7 on 2019-03-20 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190314_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 17, 54, 51, 986651, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
