# Generated by Django 2.1.7 on 2019-03-27 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20190326_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 19, 45, 9, 689702, tzinfo=utc), null=True),
        ),
    ]
