# Generated by Django 2.1.7 on 2019-07-21 03:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20190514_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 5, 23, 11, 186047, tzinfo=utc), null=True),
        ),
    ]
