# Generated by Django 2.1.7 on 2019-08-03 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20190720_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 23, 3, 27, 511885, tzinfo=utc), null=True),
        ),
    ]
