# Generated by Django 2.1.7 on 2019-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('question', models.CharField(default='', max_length=255)),
                ('answer', models.TextField(default='')),
            ],
            options={
                'ordering': ('question', 'created_at'),
            },
        ),
    ]
