# Generated by Django 2.1.7 on 2019-07-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ('id', 'question', 'created_at')},
        ),
    ]
