# Generated by Django 2.1.7 on 2019-03-27 17:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinfo',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='nss',
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='emergency_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
