# Generated by Django 2.1.7 on 2019-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_card', '0004_auto_20190404_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='organ_donor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
