# Generated by Django 2.1.7 on 2019-05-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_card', '0005_cardinfo_organ_donor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardinfo',
            options={'verbose_name_plural': 'Card info'},
        ),
    ]
