# Generated by Django 2.1.7 on 2019-04-30 17:44

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, upload_to=support.models.get_upload_path, validators=[support.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, upload_to=support.models.get_upload_path, validators=[support.models.validate_file_type]),
        ),
    ]
